apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins-port
    port: 8080
    targetPort: 8080
    nodePort:
    protocol: TCP
  type: NodePort
